services:
  vacancies-alert:
    image: ghcr.io/alexgamm/vacancies-alert/vacancies-alert:latest
    restart: unless-stopped
    env_file: .env
    labels:
      traefik.enable: true
      traefik.docker.network: chilldrill_chilldrill
      traefik.http.services.vacancies-alert.loadbalancer.server.port: 8080
      traefik.http.routers.vacancies-alert.entrypoints: websecure
      traefik.http.routers.vacancies-alert.tls.certresolver: chilldrill
      traefik.http.routers.vacancies-alert.rule: "Host(`hh.chilldrill.fun`)"
    networks:
      - chilldrill_chilldrill

networks:
  chilldrill_chilldrill:
    external: true

# gradle build
# docker build . -t ghcr.io/alexgamm/vacancies-alert/vacancies-alert:latest
# docker push ghcr.io/alexgamm/vacancies-alert/vacancies-alert:latest
# set DOCKER_HOST=ssh://sasha@94.131.100... (IN CMD!)
# docker compose pull
# docker compose up -d (should respond "Recreated")

# docker ps
# docker logs -f -n 100 vacancies-alert-vacancies-alert-1